apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calculator2
  template:
    metadata:
      labels:
        app: calculator2
    spec:
      containers:
        - name: calculator2
          image: __IMAGE__
          ports:
            - containerPort: 8080
